# Permalinks
#
# Use of `relative_permalinks` ensures post links from the index work properly.
permalink:           pretty
relative_permalinks: true

# Setup
title:               Idling Mind
tagline:             'A Mechanical Engineer with a flare to write code'
description:         'I am a mechanical engineer working at GKN aerospace. I love anything pretty, be it a website, a photograph, an art piece.... and so on. And I am really excited if I am able to create one myself.'
url:                 http://idling-mind.github.io
baseurl:             ''
paginate:            5

# About/contact
author:
  name:              Najeem Muhammed
  url:               https://twitter.com/najeem
  email:             najeem@gmail.com

# Custom vars
version:             1.0.0
