# Permalinks
#
# Use of `relative_permalinks` ensures post links from the index work properly.
permalink:           pretty
relative_permalinks: true

# Setup
title:               Idling Mind
tagline:             'Random muses of an idle mind'
description:         'This is 21st Century. Everybody should be able to write code, even a mechanical engineer like me. I get pretty excited about quite a lot of things, especially if its anything creative. Here are some of my random muses'
url:                 http://idling-mind.github.io
baseurl:             'http://idling-mind.github.io'
paginate:            5
bannerurl:           '/assets/images/sunset.jpg'

# gems
gems:                
  - jekyll-sitemap

# About/contact
author:
  name:              Najeem Muhammed
  url:               https://twitter.com/najeem
  email:             najeem@gmail.com

# Custom vars
version:             1.0.0
