# Permalinks
#
# Use of `relative_permalinks` ensures post links from the index work properly.
permalink:           pretty
relative_permalinks: true

# Setup
title:               Idling Mind
tagline:             'A Mechanical Engineer who loves to write some code'
description:         'This is 21st Century. Everybody should be able to write code, even a mechanical engineer. Heres some of my muses'
url:                 http://idling-mind.github.io
baseurl:             ''
paginate:            5

# About/contact
author:
  name:              Najeem Muhammed
  url:               https://twitter.com/najeem
  email:             najeem@gmail.com

# Custom vars
version:             1.0.0
